spring:
  kafka:
    bootstrap-servers: kafka-svc.kafka-ns:9094
  data:
    mongodb:
      uri: mongodb://admin:admin@scpi-invest-partner-db:27017/scpi-invest-partner-db?authSource=admin




logging:
  level:
    co.elastic.apm: OFF

