apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-invest-partner
  labels:
    app: scpi-invest-partner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-invest-partner
  template:
    metadata:
      name: scpi-invest-partner
      labels:
        app: scpi-invest-partner
    spec:
      containers:
        - name: scpi-invest-partner
          image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value:  "{{.Values.application.environment }}"
          envFrom:
            - secretRef:
                name: api-db-credentials
